### ISSUE TITLE
Map Pin Picker for Web

### ISSUE THREAD

**Issue by irinafilipenko** [ahmedelsayed96/ahmedelsayed96#1]
Please help me) How to use the library without google_maps_flutter.dart. Since I have a web version and I use google_maps: ^6.1.0

**Comment by ahmedelsayed96** [comment]
Can you show me how you used it

**Comment by irinafilipenko** [comment]
import 'package:flutter/material.dart';
import 'package:map_picker/map_picker.dart';
import 'package:geocoding/geocoding.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'dart:html';
import 'dart:ui' as ui;
import 'package:google_maps/google_maps.dart' as mg;

final myLatlng = mg.LatLng(1.3521, 103.8198);

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  // final _controller = Completer<GoogleMapController>();
  MapPickerController mapPickerController = MapPickerController();

  // CameraPosition cameraPosition = const CameraPosition(
  //   target: LatLng(41.311158, 69.279737),
  //   zoom: 14.4746,
  // );

  var textController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        alignment: Alignment.topCenter,
        children: [
          MapPicker(
            // pass icon widget
            iconWidget: SvgPicture.asset(
              "assets/location_icon.svg",
              height: 60,
            ),
            //add map picker controller
            mapPickerController: mapPickerController,
            child: getMap(),
            //   child: GoogleMap(
            //     myLocationEnabled: true,
            //     zoomControlsEnabled: false,
            //     // hide location button
            //     myLocationButtonEnabled: false,
            //     mapType: MapType.normal,
            //     //  camera position
            //     initialCameraPosition: cameraPosition,
            //     onMapCreated: (GoogleMapController controller) {
            //       _controller.complete(controller);
            //     },
            //     onCameraMoveStarted: () {
            //       // notify map is moving
            //       mapPickerController.mapMoving!();
            //       textController.text = "checking ...";
            //     },
            //     onCameraMove: (cameraPosition) {
            //       this.cameraPosition = cameraPosition;
            //     },
            //     onCameraIdle: () async {
            //       // notify map stopped moving
            //       mapPickerController.mapFinishedMoving!();
            //       //get address name from camera position
            //       List<Placemark> placemarks = await
placemarkFromCoordinates(
            //         cameraPosition.target.latitude,
            //         cameraPosition.target.longitude,
            //       );
            //
            //       // update the ui with the address
            //       textController.text =
            //       '${placemarks.first.name},
${placemarks.first.administrativeArea}, ${placemarks.first.country}';
            //     },
            //   ),
          ),
          Positioned(
            top: MediaQuery.of(context).viewPadding.top + 20,
            width: MediaQuery.of(context).size.width - 50,
            height: 50,
            child: TextFormField(
              maxLines: 3,
              textAlign: TextAlign.center,
              readOnly: true,
              decoration: const InputDecoration(
                  contentPadding: EdgeInsets.zero, border: InputBorder.none),
              controller: textController,
            ),
          ),
          Positioned(
            bottom: 24,
            left: 24,
            right: 24,
            child: SizedBox(
              height: 50,
              child: TextButton(
                child: const Text(
                  "Submit",
                  style: TextStyle(
                    fontWeight: FontWeight.w400,
                    fontStyle: FontStyle.normal,
                    color: Color(0xFFFFFFFF),
                    fontSize: 19,
                    // height: 19/19,
                  ),
                ),
                onPressed: () {
                  print(myLatlng);
                  //   print(
                  //       "Location ${cameraPosition.target.latitude}
${cameraPosition.target.longitude}");
                  //   print("Address: ${textController.text}");
                },
                style: ButtonStyle(
                  backgroundColor:
                      MaterialStateProperty.all<Color>(const Color(0xFFA3080C)),
                  shape: MaterialStateProperty.all<RoundedRectangleBorder>(
                    RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15.0),
                    ),
                  ),
                ),
              ),
            ),
          )
        ],
      ),
    );
  }
}

Widget getMap() {
  String htmlId = "7";

  // ignore: undefined_prefixed_name
  ui.platformViewRegistry.registerViewFactory(htmlId, (int viewId) {
    final mapOptions = mg.MapOptions()
      ..mapTypeControl = false
      ..zoom = 10
      ..center = mg.LatLng(1.3521, 103.8198);

    final elem = DivElement()
      ..id = htmlId
      ..style.width = "100%"
      ..style.height = "100%"
      ..style.border = 'none';

    final map = mg.GMap(elem, mapOptions);

    mg.Marker(mg.MarkerOptions()
      ..position = myLatlng
      ..map = map
      ..title = 'Hello World!');

    return elem;
  });

  return HtmlElementView(viewType: htmlId);
}


чт, 2 июн. 2022 г. в 11:56, Ahmed El-Sayed Ali ***@***.***>:

**Comment by irinafilipenko** [comment]
import 'package:flutter/material.dart';
import 'package:map_picker/map_picker.dart';
import 'package:geocoding/geocoding.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'dart:html';
import 'dart:ui' as ui;
import 'package:google_maps/google_maps.dart' as mg;



class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  // final _controller = Completer<GoogleMapController>();
  MapPickerController mapPickerController = MapPickerController();

  // CameraPosition cameraPosition = const CameraPosition(
  //   target: LatLng(41.311158, 69.279737),
  //   zoom: 14.4746,
  // );

  var textController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        alignment: Alignment.topCenter,
        children: [
          MapPicker(
            // pass icon widget
            iconWidget: Icon(
              Icons.location_pin,
              size: 50,
            ),
            //add map picker controller
            mapPickerController: mapPickerController,
            child: getMap(),
            //   child: GoogleMap(
            //     myLocationEnabled: true,
            //     zoomControlsEnabled: false,
            //     // hide location button
            //     myLocationButtonEnabled: false,
            //     mapType: MapType.normal,
            //     //  camera position
            //     initialCameraPosition: cameraPosition,
            //     onMapCreated: (GoogleMapController controller) {
            //       _controller.complete(controller);
            //     },
            //     onCameraMoveStarted: () {
            //       // notify map is moving
            //       mapPickerController.mapMoving!();
            //       textController.text = "checking ...";
            //     },
            //     onCameraMove: (cameraPosition) {
            //       this.cameraPosition = cameraPosition;
            //     },
            //     onCameraIdle: () async {
            //       // notify map stopped moving
            //       mapPickerController.mapFinishedMoving!();
            //       //get address name from camera position
            //       List<Placemark> placemarks = await
placemarkFromCoordinates(
            //         cameraPosition.target.latitude,
            //         cameraPosition.target.longitude,
            //       );
            //
            //       // update the ui with the address
            //       textController.text =
            //       '${placemarks.first.name},
${placemarks.first.administrativeArea}, ${placemarks.first.country}';
            //     },
            //   ),
          ),
          Positioned(
            top: MediaQuery.of(context).viewPadding.top + 20,
            width: MediaQuery.of(context).size.width - 50,
            height: 50,
            child: TextFormField(
              maxLines: 3,
              textAlign: TextAlign.center,
              readOnly: true,
              decoration: const InputDecoration(
                  contentPadding: EdgeInsets.zero, border: InputBorder.none),
              controller: textController,
            ),
          ),
          Positioned(
            bottom: 24,
            left: 24,
            right: 24,
            child: SizedBox(
              height: 50,
              child: TextButton(
                child: const Text(
                  "Submit",
                  style: TextStyle(
                    fontWeight: FontWeight.w400,
                    fontStyle: FontStyle.normal,
                    color: Color(0xFFFFFFFF),
                    fontSize: 19,
                    // height: 19/19,
                  ),
                ),
                onPressed: () {
                  //   print(
                  //       "Location ${cameraPosition.target.latitude}
${cameraPosition.target.longitude}");
                  //   print("Address: ${textController.text}");
                },
                style: ButtonStyle(
                  backgroundColor:
                      MaterialStateProperty.all<Color>(const Color(0xFFA3080C)),
                  shape: MaterialStateProperty.all<RoundedRectangleBorder>(
                    RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15.0),
                    ),
                  ),
                ),
              ),
            ),
          )
        ],
      ),
    );
  }
}

Widget getMap() {
  String htmlId = "7";

  // ignore: undefined_prefixed_name
  ui.platformViewRegistry.registerViewFactory(htmlId, (int viewId) {
    final mapOptions = mg.MapOptions()
      ..mapTypeControl = false
      ..zoom = 10
      ..center = mg.LatLng(1.3521, 103.8198);

    final elem = DivElement()
      ..id = htmlId
      ..style.width = "100%"
      ..style.height = "100%"
      ..style.border = 'none';

    final map = mg.GMap(elem, mapOptions);

    // mg.Marker(mg.MarkerOptions()
    //   ..position = myLatlng
    //   ..map = map
    //   ..title = 'Hello World!');

    return elem;
  });

  return HtmlElementView(viewType: htmlId);
}


чт, 2 июн. 2022 г. в 14:33, Irina Filipenko ***@***.***>:

**Comment by irinafilipenko** [comment]
Good afternoon, I redid the marker, but I don’t understand how to get
coordinates without using cameraPosition



чт, 2 июн. 2022 г. в 15:01, Irina Filipenko ***@***.***>:

**Comment by ahmedelsayed96** [comment]
Can you listen to the map camera movements?
